namespace: production
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
commonLabels:
  app.kubernetes.io/name: altdaservice
images:
- name: vonwig/altdaservice
  newTag: v9
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
decryption:
  provider: sops
  secretRef:
    name: sops-gpg
